/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdsRouteImport } from './routes/ads'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as NetworkRouteImport } from './routes/network'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as PlansRouteImport } from './routes/plans'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as WithdrawRouteImport } from './routes/withdraw'
import { Route as DepositPlanIdRouteImport } from './routes/deposit.$planId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdsRoute = AdsRouteImport.update({
  id: '/ads',
  path: '/ads',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const NetworkRoute = NetworkRouteImport.update({
  id: '/network',
  path: '/network',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const PlansRoute = PlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const WithdrawRoute = WithdrawRouteImport.update({
  id: '/withdraw',
  path: '/withdraw',
  getParentRoute: () => rootRouteImport,
} as any)
const DepositPlanIdRoute = DepositPlanIdRouteImport.update({
  id: '/deposit/$planId',
  path: '/deposit/$planId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ads': typeof AdsRoute
  '/auth': typeof AuthRoute
  '/history': typeof HistoryRoute
  '/network': typeof NetworkRoute
  '/notifications': typeof NotificationsRoute
  '/plans': typeof PlansRoute
  '/profile': typeof ProfileRoute
  '/withdraw': typeof WithdrawRoute
  '/deposit/$planId': typeof DepositPlanIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ads': typeof AdsRoute
  '/auth': typeof AuthRoute
  '/history': typeof HistoryRoute
  '/network': typeof NetworkRoute
  '/notifications': typeof NotificationsRoute
  '/plans': typeof PlansRoute
  '/profile': typeof ProfileRoute
  '/withdraw': typeof WithdrawRoute
  '/deposit/$planId': typeof DepositPlanIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ads': typeof AdsRoute
  '/auth': typeof AuthRoute
  '/history': typeof HistoryRoute
  '/network': typeof NetworkRoute
  '/notifications': typeof NotificationsRoute
  '/plans': typeof PlansRoute
  '/profile': typeof ProfileRoute
  '/withdraw': typeof WithdrawRoute
  '/deposit/$planId': typeof DepositPlanIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ads'
    | '/auth'
    | '/history'
    | '/network'
    | '/notifications'
    | '/plans'
    | '/profile'
    | '/withdraw'
    | '/deposit/$planId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ads'
    | '/auth'
    | '/history'
    | '/network'
    | '/notifications'
    | '/plans'
    | '/profile'
    | '/withdraw'
    | '/deposit/$planId'
  id:
    | '__root__'
    | '/'
    | '/ads'
    | '/auth'
    | '/history'
    | '/network'
    | '/notifications'
    | '/plans'
    | '/profile'
    | '/withdraw'
    | '/deposit/$planId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdsRoute: typeof AdsRoute
  AuthRoute: typeof AuthRoute
  HistoryRoute: typeof HistoryRoute
  NetworkRoute: typeof NetworkRoute
  NotificationsRoute: typeof NotificationsRoute
  PlansRoute: typeof PlansRoute
  ProfileRoute: typeof ProfileRoute
  WithdrawRoute: typeof WithdrawRoute
  DepositPlanIdRoute: typeof DepositPlanIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ads': {
      id: '/ads'
      path: '/ads'
      fullPath: '/ads'
      preLoaderRoute: typeof AdsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/network': {
      id: '/network'
      path: '/network'
      fullPath: '/network'
      preLoaderRoute: typeof NetworkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plans': {
      id: '/plans'
      path: '/plans'
      fullPath: '/plans'
      preLoaderRoute: typeof PlansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/withdraw': {
      id: '/withdraw'
      path: '/withdraw'
      fullPath: '/withdraw'
      preLoaderRoute: typeof WithdrawRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deposit/$planId': {
      id: '/deposit/$planId'
      path: '/deposit/$planId'
      fullPath: '/deposit/$planId'
      preLoaderRoute: typeof DepositPlanIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdsRoute: AdsRoute,
  AuthRoute: AuthRoute,
  HistoryRoute: HistoryRoute,
  NetworkRoute: NetworkRoute,
  NotificationsRoute: NotificationsRoute,
  PlansRoute: PlansRoute,
  ProfileRoute: ProfileRoute,
  WithdrawRoute: WithdrawRoute,
  DepositPlanIdRoute: DepositPlanIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
