/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthenticatedAdsRouteImport } from './routes/_authenticated.ads'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedHistoryRouteImport } from './routes/_authenticated.history'
import { Route as AuthenticatedNetworkRouteImport } from './routes/_authenticated.network'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated.notifications'
import { Route as AuthenticatedPlansRouteImport } from './routes/_authenticated.plans'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated.profile'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as AuthenticatedSupportRouteImport } from './routes/_authenticated.support'
import { Route as AuthenticatedWithdrawRouteImport } from './routes/_authenticated.withdraw'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as ApiUploadHeroRouteImport } from './routes/api.upload-hero'
import { Route as ApiImpersonationConsumeRouteImport } from './routes/api.impersonation.consume'
import { Route as AuthenticatedDepositPlanIdRouteImport } from './routes/_authenticated.deposit.$planId'
import { Route as JoinReferralCodeRouteImport } from './routes/join.$referralCode'
import { Route as AuthenticatedUsersDetailPublicUidRouteImport } from './routes/_authenticated.users.detail.$publicUid'

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdsRoute = AuthenticatedAdsRouteImport.update({
  id: '/_authenticated/ads',
  path: '/ads',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedHistoryRoute = AuthenticatedHistoryRouteImport.update({
  id: '/_authenticated/history',
  path: '/history',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedNetworkRoute = AuthenticatedNetworkRouteImport.update({
  id: '/_authenticated/network',
  path: '/network',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedNotificationsRoute = AuthenticatedNotificationsRouteImport.update({
  id: '/_authenticated/notifications',
  path: '/notifications',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPlansRoute = AuthenticatedPlansRouteImport.update({
  id: '/_authenticated/plans',
  path: '/plans',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/_authenticated/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSupportRoute = AuthenticatedSupportRouteImport.update({
  id: '/_authenticated/support',
  path: '/support',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedWithdrawRoute = AuthenticatedWithdrawRouteImport.update({
  id: '/_authenticated/withdraw',
  path: '/withdraw',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const ApiUploadHeroRoute = ApiUploadHeroRouteImport.update({
  id: '/api/upload-hero',
  path: '/api/upload-hero',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiImpersonationConsumeRoute = ApiImpersonationConsumeRouteImport.update({
  id: '/api/impersonation/consume',
  path: '/api/impersonation/consume',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDepositPlanIdRoute = AuthenticatedDepositPlanIdRouteImport.update({
  id: '/_authenticated/deposit/$planId',
  path: '/deposit/$planId',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedUsersDetailPublicUidRoute = AuthenticatedUsersDetailPublicUidRouteImport.update({
  id: '/_authenticated/users/detail/$publicUid',
  path: '/users/detail/$publicUid',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const JoinReferralCodeRoute = JoinReferralCodeRouteImport.update({
  id: '/join/$referralCode',
  path: '/join/$referralCode',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/ads': typeof AdsRoute
  '/auth': typeof AuthRoute
  '/history': typeof HistoryRoute
  '/network': typeof NetworkRoute
  '/notifications': typeof NotificationsRoute
  '/plans': typeof PlansRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/support': typeof SupportRoute
  '/withdraw': typeof WithdrawRoute
  '/admin/login': typeof AdminLoginRoute
  '/api/upload-hero': typeof ApiUploadHeroRoute
  '/api/impersonation/consume': typeof ApiImpersonationConsumeRoute
  '/deposit/$planId': typeof DepositPlanIdRoute
  '/join/$referralCode': typeof JoinReferralCodeRoute
  '/users/detail/$publicUid': typeof UsersDetailPublicUidRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/ads': typeof AdsRoute
  '/auth': typeof AuthRoute
  '/history': typeof HistoryRoute
  '/network': typeof NetworkRoute
  '/notifications': typeof NotificationsRoute
  '/plans': typeof PlansRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/support': typeof SupportRoute
  '/withdraw': typeof WithdrawRoute
  '/admin/login': typeof AdminLoginRoute
  '/api/upload-hero': typeof ApiUploadHeroRoute
  '/api/impersonation/consume': typeof ApiImpersonationConsumeRoute
  '/deposit/$planId': typeof DepositPlanIdRoute
  '/join/$referralCode': typeof JoinReferralCodeRoute
  '/users/detail/$publicUid': typeof UsersDetailPublicUidRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/ads': typeof AdsRoute
  '/auth': typeof AuthRoute
  '/history': typeof HistoryRoute
  '/network': typeof NetworkRoute
  '/notifications': typeof NotificationsRoute
  '/plans': typeof PlansRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/support': typeof SupportRoute
  '/withdraw': typeof WithdrawRoute
  '/admin/login': typeof AdminLoginRoute
  '/api/upload-hero': typeof ApiUploadHeroRoute
  '/api/impersonation/consume': typeof ApiImpersonationConsumeRoute
  '/deposit/$planId': typeof DepositPlanIdRoute
  '/join/$referralCode': typeof JoinReferralCodeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/_authenticated/ads'
    | '/auth'
    | '/_authenticated/history'
    | '/_authenticated/network'
    | '/_authenticated/notifications'
    | '/_authenticated/plans'
    | '/_authenticated/profile'
    | '/reset-password'
    | '/signup'
    | '/_authenticated/support'
    | '/_authenticated/withdraw'
    | '/admin/login'
    | '/api/upload-hero'
    | '/api/impersonation/consume'
    | '/_authenticated/deposit/$planId'
    | '/join/$referralCode'
    | '/_authenticated/users/detail/$publicUid'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/ads'
    | '/auth'
    | '/history'
    | '/network'
    | '/notifications'
    | '/plans'
    | '/profile'
    | '/reset-password'
    | '/signup'
    | '/support'
    | '/withdraw'
    | '/admin/login'
    | '/api/upload-hero'
    | '/api/impersonation/consume'
    | '/deposit/$planId'
    | '/join/$referralCode'
    | '/users/detail/$publicUid'
  id:
    | '/_authenticated'
    | '__root__'
    | '/'
    | '/admin'
    | '/ads'
    | '/auth'
    | '/history'
    | '/network'
    | '/notifications'
    | '/plans'
    | '/profile'
    | '/reset-password'
    | '/signup'
    | '/support'
    | '/withdraw'
    | '/admin/login'
    | '/api/upload-hero'
    | '/api/impersonation/consume'
    | '/deposit/$planId'
    | '/join/$referralCode'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  ApiUploadHeroRoute: typeof ApiUploadHeroRoute
  ApiImpersonationConsumeRoute: typeof ApiImpersonationConsumeRoute
  JoinReferralCodeRoute: typeof JoinReferralCodeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ads': {
      id: '/_authenticated/ads'
      path: '/ads'
      fullPath: '/ads'
      preLoaderRoute: typeof AdsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/_authenticated/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/network': {
      id: '/_authenticated/network'
      path: '/network'
      fullPath: '/network'
      preLoaderRoute: typeof NetworkRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/plans': {
      id: '/_authenticated/plans'
      path: '/plans'
      fullPath: '/plans'
      preLoaderRoute: typeof PlansRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/_authenticated/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/withdraw': {
      id: '/_authenticated/withdraw'
      path: '/withdraw'
      fullPath: '/withdraw'
      preLoaderRoute: typeof WithdrawRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/upload-hero': {
      id: '/api/upload-hero'
      path: '/api/upload-hero'
      fullPath: '/api/upload-hero'
      preLoaderRoute: typeof ApiUploadHeroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/impersonation/consume': {
      id: '/api/impersonation/consume'
      path: '/api/impersonation/consume'
      fullPath: '/api/impersonation/consume'
      preLoaderRoute: typeof ApiImpersonationConsumeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deposit/$planId': {
      id: '/_authenticated/deposit/$planId'
      path: '/deposit/$planId'
      fullPath: '/deposit/$planId'
      preLoaderRoute: typeof DepositPlanIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/users/detail/$publicUid': {
      id: '/_authenticated/users/detail/$publicUid'
      path: '/users/detail/$publicUid'
      fullPath: '/users/detail/$publicUid'
      preLoaderRoute: typeof UsersDetailPublicUidRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/join/$referralCode': {
      id: '/join/$referralCode'
      path: '/join/$referralCode'
      fullPath: '/join/$referralCode'
      preLoaderRoute: typeof JoinReferralCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminLoginRoute: typeof AdminLoginRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminLoginRoute: AdminLoginRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAdsRoute: typeof AuthenticatedAdsRoute
  AuthenticatedHistoryRoute: typeof AuthenticatedHistoryRoute
  AuthenticatedNetworkRoute: typeof AuthenticatedNetworkRoute
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedPlansRoute: typeof AuthenticatedPlansRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedSupportRoute: typeof AuthenticatedSupportRoute
  AuthenticatedWithdrawRoute: typeof AuthenticatedWithdrawRoute
  AuthenticatedDepositPlanIdRoute: typeof AuthenticatedDepositPlanIdRoute
  AuthenticatedUsersDetailPublicUidRoute: typeof AuthenticatedUsersDetailPublicUidRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdsRoute: AuthenticatedAdsRoute
  AuthenticatedHistoryRoute: AuthenticatedHistoryRoute
  AuthenticatedNetworkRoute: AuthenticatedNetworkRoute
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute
  AuthenticatedPlansRoute: AuthenticatedPlansRoute
  AuthenticatedProfileRoute: AuthenticatedProfileRoute
  AuthenticatedSupportRoute: AuthenticatedSupportRoute
  AuthenticatedWithdrawRoute: AuthenticatedWithdrawRoute
  AuthenticatedDepositPlanIdRoute: AuthenticatedDepositPlanIdRoute
  AuthenticatedUsersDetailPublicUidRoute: AuthenticatedUsersDetailPublicUidRoute
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(AuthenticatedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AdsRoute: AdsRoute,
  AuthRoute: AuthRoute,
  HistoryRoute: HistoryRoute,
  NetworkRoute: NetworkRoute,
  NotificationsRoute: NotificationsRoute,
  PlansRoute: PlansRoute,
  ProfileRoute: ProfileRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  SupportRoute: SupportRoute,
  WithdrawRoute: WithdrawRoute,
  ApiUploadHeroRoute: ApiUploadHeroRoute,
  ApiImpersonationConsumeRoute: ApiImpersonationConsumeRoute,
  DepositPlanIdRoute: DepositPlanIdRoute,
  JoinReferralCodeRoute: JoinReferralCodeRoute,
  UsersDetailPublicUidRoute: UsersDetailPublicUidRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
