/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AdsRouteImport } from './routes/ads'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as NetworkRouteImport } from './routes/network'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as PlansRouteImport } from './routes/plans'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SupportRouteImport } from './routes/support'
import { Route as WithdrawRouteImport } from './routes/withdraw'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as ApiUploadHeroRouteImport } from './routes/api.upload-hero'
import { Route as DepositPlanIdRouteImport } from './routes/deposit.$planId'
import { Route as JoinReferralCodeRouteImport } from './routes/join.$referralCode'
import { Route as UsersDetailPublicUidRouteImport } from './routes/users.detail.$publicUid'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdsRoute = AdsRouteImport.update({
  id: '/ads',
  path: '/ads',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const NetworkRoute = NetworkRouteImport.update({
  id: '/network',
  path: '/network',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const PlansRoute = PlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const WithdrawRoute = WithdrawRouteImport.update({
  id: '/withdraw',
  path: '/withdraw',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const ApiUploadHeroRoute = ApiUploadHeroRouteImport.update({
  id: '/api/upload-hero',
  path: '/api/upload-hero',
  getParentRoute: () => rootRouteImport,
} as any)
const DepositPlanIdRoute = DepositPlanIdRouteImport.update({
  id: '/deposit/$planId',
  path: '/deposit/$planId',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersDetailPublicUidRoute = UsersDetailPublicUidRouteImport.update({
  id: '/users/detail/$publicUid',
  path: '/users/detail/$publicUid',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinReferralCodeRoute = JoinReferralCodeRouteImport.update({
  id: '/join/$referralCode',
  path: '/join/$referralCode',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/ads': typeof AdsRoute
  '/auth': typeof AuthRoute
  '/history': typeof HistoryRoute
  '/network': typeof NetworkRoute
  '/notifications': typeof NotificationsRoute
  '/plans': typeof PlansRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/support': typeof SupportRoute
  '/withdraw': typeof WithdrawRoute
  '/admin/login': typeof AdminLoginRoute
  '/api/upload-hero': typeof ApiUploadHeroRoute
  '/deposit/$planId': typeof DepositPlanIdRoute
  '/join/$referralCode': typeof JoinReferralCodeRoute
  '/users/detail/$publicUid': typeof UsersDetailPublicUidRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/ads': typeof AdsRoute
  '/auth': typeof AuthRoute
  '/history': typeof HistoryRoute
  '/network': typeof NetworkRoute
  '/notifications': typeof NotificationsRoute
  '/plans': typeof PlansRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/support': typeof SupportRoute
  '/withdraw': typeof WithdrawRoute
  '/admin/login': typeof AdminLoginRoute
  '/api/upload-hero': typeof ApiUploadHeroRoute
  '/deposit/$planId': typeof DepositPlanIdRoute
  '/join/$referralCode': typeof JoinReferralCodeRoute
  '/users/detail/$publicUid': typeof UsersDetailPublicUidRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/ads': typeof AdsRoute
  '/auth': typeof AuthRoute
  '/history': typeof HistoryRoute
  '/network': typeof NetworkRoute
  '/notifications': typeof NotificationsRoute
  '/plans': typeof PlansRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/support': typeof SupportRoute
  '/withdraw': typeof WithdrawRoute
  '/admin/login': typeof AdminLoginRoute
  '/api/upload-hero': typeof ApiUploadHeroRoute
  '/deposit/$planId': typeof DepositPlanIdRoute
  '/join/$referralCode': typeof JoinReferralCodeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/ads'
    | '/auth'
    | '/history'
    | '/network'
    | '/notifications'
    | '/plans'
    | '/profile'
    | '/reset-password'
    | '/signup'
    | '/support'
    | '/withdraw'
    | '/admin/login'
    | '/api/upload-hero'
    | '/deposit/$planId'
    | '/join/$referralCode'
    | '/users/detail/$publicUid'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/ads'
    | '/auth'
    | '/history'
    | '/network'
    | '/notifications'
    | '/plans'
    | '/profile'
    | '/reset-password'
    | '/signup'
    | '/support'
    | '/withdraw'
    | '/admin/login'
    | '/api/upload-hero'
    | '/deposit/$planId'
    | '/join/$referralCode'
    | '/users/detail/$publicUid'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/ads'
    | '/auth'
    | '/history'
    | '/network'
    | '/notifications'
    | '/plans'
    | '/profile'
    | '/reset-password'
    | '/signup'
    | '/support'
    | '/withdraw'
    | '/admin/login'
    | '/api/upload-hero'
    | '/deposit/$planId'
    | '/join/$referralCode'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AdsRoute: typeof AdsRoute
  AuthRoute: typeof AuthRoute
  HistoryRoute: typeof HistoryRoute
  NetworkRoute: typeof NetworkRoute
  NotificationsRoute: typeof NotificationsRoute
  PlansRoute: typeof PlansRoute
  ProfileRoute: typeof ProfileRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  SupportRoute: typeof SupportRoute
  WithdrawRoute: typeof WithdrawRoute
  ApiUploadHeroRoute: typeof ApiUploadHeroRoute
  DepositPlanIdRoute: typeof DepositPlanIdRoute
  JoinReferralCodeRoute: typeof JoinReferralCodeRoute
  UsersDetailPublicUidRoute: typeof UsersDetailPublicUidRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ads': {
      id: '/ads'
      path: '/ads'
      fullPath: '/ads'
      preLoaderRoute: typeof AdsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/network': {
      id: '/network'
      path: '/network'
      fullPath: '/network'
      preLoaderRoute: typeof NetworkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plans': {
      id: '/plans'
      path: '/plans'
      fullPath: '/plans'
      preLoaderRoute: typeof PlansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/withdraw': {
      id: '/withdraw'
      path: '/withdraw'
      fullPath: '/withdraw'
      preLoaderRoute: typeof WithdrawRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/upload-hero': {
      id: '/api/upload-hero'
      path: '/api/upload-hero'
      fullPath: '/api/upload-hero'
      preLoaderRoute: typeof ApiUploadHeroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deposit/$planId': {
      id: '/deposit/$planId'
      path: '/deposit/$planId'
      fullPath: '/deposit/$planId'
      preLoaderRoute: typeof DepositPlanIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users/detail/$publicUid': {
      id: '/users/detail/$publicUid'
      path: '/users/detail/$publicUid'
      fullPath: '/users/detail/$publicUid'
      preLoaderRoute: typeof UsersDetailPublicUidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join/$referralCode': {
      id: '/join/$referralCode'
      path: '/join/$referralCode'
      fullPath: '/join/$referralCode'
      preLoaderRoute: typeof JoinReferralCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminLoginRoute: typeof AdminLoginRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminLoginRoute: AdminLoginRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AdsRoute: AdsRoute,
  AuthRoute: AuthRoute,
  HistoryRoute: HistoryRoute,
  NetworkRoute: NetworkRoute,
  NotificationsRoute: NotificationsRoute,
  PlansRoute: PlansRoute,
  ProfileRoute: ProfileRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  SupportRoute: SupportRoute,
  WithdrawRoute: WithdrawRoute,
  ApiUploadHeroRoute: ApiUploadHeroRoute,
  DepositPlanIdRoute: DepositPlanIdRoute,
  JoinReferralCodeRoute: JoinReferralCodeRoute,
  UsersDetailPublicUidRoute: UsersDetailPublicUidRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
